<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MarcasComerciaisSeeder extends Seeder
{
    public function run()
    {
        $marcas = ['BRADDOCK WG', 'BRADDOCK K', 'MIRA 900 WG', 'MOL 2,4 D', 'VENIA BR', 'CARTAGO OU ', 'OPTIBEX', 'PREVENT GOLD', 'TREMOR', 'FULLGUARD', 'SULBAN', 'MASTERTRIONA', 'A  DEFINIR', 'CLOMASTER', 'ZETA', 'RYFLI', 'FLUTOX ', 'AMAIZ', 'DERRETE', 'DAGA', 'GARANHÃO', 'SURRATEIRO', 'TRABUCO ', 'KIT TRABUCO ', 'TALLADEGA', 'MISTER', 'VALENTE BR', 'CUTLASS', 'ZAPRET', 'IMIDACLOPRID HAILER 600 FS', 'CLORPIRIFÓS FERSOL', 'CLORPIRIFÓS GHARDA', 'FECYDE', 'VIVANTHA', 'INSTAL ', 'FIPRONIL GHARDA 800 WG', 'LUFENURON 50', 'ETIPROLE 200', 'PIRADO / ADVER', 'METOMIL 215', 'DIAFENTIUROM 500', 'USER 430 BR', 'STIVA', 'ELEGANCE 500 SC', 'TEBURAZ', 'CONTROL T', 'KIT GUARDIAN', 'DOTTE', 'SIDRAK', 'BOX CROPBIO PHOS', 'CROPBIO AZOS', 'CROPBIO SOJA 7x10ˆ9', 'CROPBIO TURFA', 'NEMATHA (B. amyloliquefaciens)', 'BEAUVEBIO (Beauveria bassiana)', 'TRICHOKING (T. asperellum)', 'CHOLLA (B. aryabhattai)', 'ACORDE', 'ACORDE TABACO', 'CROP CMA GRAM', 'CROP CMA Ni', 'BOROGÊNIO', 'CAB 8:2', 'COMONI', 'COMOZin', 'COMO FERT', 'CROP 30 ', 'CROP 30 BR', 'CROP ACTIVE Mn', 'CROP POTASSIUM ULTRA', 'ENDURANCE', 'MANGANÊS 150', 'MAX MOL', 'NITROMAG', 'PRATICO', 'STALLION', 'STALLION ULTRA', 'TRIPLO N ', 'ZINCOGÊNIO', 'CROP ACTIVE K20 ', 'CROP DEFENDER', 'CUPROSO', 'CUPROZIN ULTRA ', 'SOLLUS MOL', 'SOLLUS MOL ULTRA', 'APPLIKER', 'BIOTINA', 'COMPAT', 'FLUXUS', 'N FIX', 'OUT ADJ', 'PROTANK', 'READY FIX', 'TERPEN', 'ULTRA FIX', 'ULTRA FIX AIR', 'ALCANCE', 'CROP OIL', 'INTENSE', 'ZOM', 'BIOFIX FORCE BLACK', 'BIOFIX FORCE BLUE', 'BIOFIX FORCE CLEAN', 'BIOFIX FORCE GREEN', 'BIOFIX FORCE RED', 'BIOFIX FORCE BLACK SHINY', 'BIOFIX FORCE BLUE SHINY', 'BIOFIX FORCE CLEAN SHINY', 'BIOFIX FORCE GREEN SHINY', 'BIOFIX FORCE RED SHINY', 'BIOFORCE RED SHINY CEREALIS', 'BIODRYER SILVER', 'BIODRYER BLACK DIAMOND 50', 'OPRESSOR', 'REMOUVER'];

        foreach ($marcas as $nome) {
            DB::table('marcas_comerciais')->updateOrInsert(
                ['nome' => $nome]
            );
        }
    }
}
