<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PrincipiosAtivosSeeder extends Seeder
{
    public function run()
    {
        $principios = ['GLIFOSATO 720 ', 'GLIFOSATO 540', 'ATRAZINA WG', '2,4 806 SL', 'DIQUAT 200', 'CLETODIN 240', 'GLUFOSINATO 880 SG', 'S-METALACLOR 960', 'FLUMIOXAZINA 480', 'CARFENTRAZONE 400', 'CLORIMURON 250', 'MESOTRIONE 480', 'CLOMAZONE 360', 'CLOMAZONE 500', 'IMAZETAPIR 106  SL', 'FOMESAFEM 250', 'ISOXAFLUTOLE 750', 'NICOSULFURON 750', 'METSULFURON METÍLICO 600', 'HALOXIFOP 120', 'BIFENTRINA 400', 'LAMBCIALOTRIN  250', 'ACETAMIPRID  125 + BIFENTRINA 125 SL', 'ACETA 250 +BIFENTRIN 400', 'ACETAMIPRID 200 SP', 'PIRIPROXIFEN  100 SL', 'ACEFATO 970 SG', 'IMIDACLOPRID 700', 'IMIDACLOPRID 500 SC', 'IMIDACLOPRID 600 SC', 'CLORPIRIFÓS 480', 'DIFLUBENZURON 480', 'TIAMETOXAN 500', 'FIPRONIL  250  TS', 'FIPRONIL 800', 'LUFENURON 50', 'ETIPROLE 200', 'CLORFENAPIR 240', 'METOMIL 215', 'DIAFENTIUROM 500', 'TEBUCONAZOLE 430', 'DIFENOCONAZOLE 250', 'FLUAZINAN 500 ', 'AZOXISTROBINA 120 + TEBUCONAZOLE 200', 'TIOFANATO METÍLICO 500', 'TEBUCO 430 + AZOXIS 250', 'PROTIOCONAZOL 240g/L + PICOXISTROBINA 200g/L', 'AZOXISTROBINA 250', ' CROPBIO ', ' BIOATIVADORES ', ' BIOATIVADORES  ', ' CROP NUTRI  ', ' INDUTORES ', ' PROTETORES ', ' CONDICIONADORES ', ' CROPTECH ', ' ÓLEOS DE ALTA PERFORMANCE ', ' POLÍMEROS ', ' PÓ SECANTE ', ' PRODUTO ORGÂNICO ', ' AGENTE LIMPANTE '];

        foreach ($principios as $nome) {
            DB::table('principios_ativos')->updateOrInsert(
                ['nome' => $nome]
            );
        }
    }
}
